services:
  - type: web
    name: weather-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
